version: '3.4'
services:

  patrimonio-bd:
    container_name: pontoeletronico-bd
    image: pontoeletronico-bd
    build: .
    ports:
      - "5432:5432"
#docker rm $(docker ps -a -f status=exited -q)